server:
  port: 8088 #server running port

---
spring:
  profiles: dev
name: TestDev

---
spring:
  profiles: pro
  application:
    name: cloud-user-service-demo # eureka上显示的服务名称标识
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root1234
    dbcp2:
      min-idle: 5 # the min survive counts connections in the pool
      initial-size: 5 # init the amount of connections
      max-total: 5 # max counts of connections
      max-wait-millis: 200 # max time to get a connection

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.xml
  type-aliases-package: com.sakura.rain.entity
  mapper-locations: classpath:mybatis/mapper/**/*.xml
